import { ApiProperty } from '@nestjs/swagger';
import {
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  Column,
  Entity,
  OneToMany,
} from 'typeorm';
import { Stage } from '../../stage/entities';

@Entity('hotel')
export class Hotel {
  @ApiProperty({
    example: 'ffa31807-f019-43d7-a2b9-d2f899784d72',
    description: 'Unique identifier (autogenerated)',
    required: false,
  })
  @PrimaryGeneratedColumn('uuid')
  public id: string;

  @CreateDateColumn({ type: 'timestamptz' })
  public createdAt: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  public updatedAt: Date;

  @ApiProperty({ example: 50.01, description: 'Longitude' })
  @Column({ type: 'double precision' })
  public longitude: number;

  @ApiProperty({ example: 0.91, description: 'Latitude' })
  @Column({ type: 'double precision' })
  public latitude: number;

  @ApiProperty({ example: 'This is a hotel', description: 'Pin Description' })
  @Column({ type: 'text' })
  public description: string;

  @ApiProperty({ example: 'Sea hotel', description: 'Hotel Name' })
  @Column({ type: 'text' })
  public name: string;

  @ApiProperty({ example: 'This is a hotel image', description: 'Hotel Image' })
  @Column({ type: 'text', nullable: true })
  public image: string;

  @OneToMany(() => Stage, (stage) => stage.hotel, { cascade: true })
  public stages: Stage[];
}
