import { ApiProperty } from '@nestjs/swagger';
import {
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  Column,
  Entity,
} from 'typeorm';

@Entity('superUser')
export class SuperUser {
  @ApiProperty({
    example: 'ffa31807-f019-43d7-a2b9-d2f899784d72',
    description: 'Unique identifier (autogenerated)',
    required: false,
  })
  @PrimaryGeneratedColumn('uuid')
  public id: string;

  @CreateDateColumn({ type: 'timestamptz' })
  public createdAt: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  public updatedAt: Date;

  @ApiProperty({ example: 'David', description: 'Super User Name' })
  @Column({ type: 'text', unique: true })
  public name: string;

  @ApiProperty({ example: 'Salmon', description: 'Super User Address Name' })
  @Column({ type: 'text' })
  public address: string;

  @ApiProperty({ example: 'ronal@gmail.com', description: 'Super User Email' })
  @Column({ type: 'text', unique: true })
  public email: string;

  @ApiProperty({ example: '0000-0000', description: 'Super User Phone' })
  @Column({ type: 'text', unique: true })
  public phone: string;

  @ApiProperty({ example: '123456', description: 'One time password' })
  @Column({ type: 'text', nullable: true })
  public otp: string;

  @ApiProperty({ example: '123456', description: 'Password' })
  @Column({ type: 'text', nullable: true })
  public password: string;

  @ApiProperty({
    example: '2021-11-29 19:40:53.876+02',
    description: 'Worker verified otp',
    required: false,
  })
  @Column({ type: 'timestamptz', nullable: true })
  public otpVerifiedAt: Date;
}
