import { ApiProperty } from '@nestjs/swagger';
import {
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  Column,
  Entity,
  ManyToOne,
  JoinColumn,
  OneToMany,
} from 'typeorm';
import { Stage } from '../../stage/entities';
import { Window } from '../../window/entities';

@Entity('room')
export class Room {
  @ApiProperty({
    example: 'ffa31807-f019-43d7-a2b9-d2f899784d72',
    description: 'Unique identifier (autogenerated)',
    required: false,
  })
  @PrimaryGeneratedColumn('uuid')
  public id: string;

  @CreateDateColumn({ type: 'timestamptz' })
  public createdAt: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  public updatedAt: Date;

  @ApiProperty({ example: 'Rest Stage', description: 'Stage Name' })
  @Column({ type: 'text' })
  public name: string;

  @ManyToOne(() => Stage, (stage) => stage.rooms, { onDelete: 'SET NULL' })
  @JoinColumn()
  public stage: Stage;

  @OneToMany(() => Window, (window) => window.room, { cascade: true })
  public windows: Window[];
}
