import { ApiProperty } from '@nestjs/swagger';
import {
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  Column,
  Entity,
  ManyToOne,
  JoinColumn,
} from 'typeorm';
import { User } from '../../user/entities';
import { Window } from '../../window/entities';
import { REQUEST, REQUEST_VALUES } from '../../../constants/request-types';

@Entity('ask-change')
export class AskChange {
  @ApiProperty({
    example: 'ffa31807-f019-43d7-a2b9-d2f899784d72',
    description: 'Unique identifier (autogenerated)',
    required: false,
  })
  @PrimaryGeneratedColumn('uuid')
  public id: string;

  @CreateDateColumn({ type: 'timestamptz' })
  public createdAt: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  public updatedAt: Date;

  @ApiProperty({
    example: REQUEST.NEW_REQUEST,
    description: 'New request for ask for change',
  })
  @Column({ type: 'enum', default: REQUEST.NEW_REQUEST, enum: REQUEST_VALUES })
  public status: REQUEST;

  @ApiProperty({
    example: 'This is admin windowComment',
    description: 'Admin Comment',
  })
  @Column({ type: 'text', nullable: true })
  public comment: string;

  @ApiProperty({
    example: 'This is a file',
    description: 'Attached by admin',
  })
  @Column({ type: 'text', nullable: true })
  public file: string;

  @ApiProperty({
    example: 'This is an originalFileName',
    description: 'Attached by admin',
  })
  @Column({ type: 'text', nullable: true })
  public originalFileName: string;

  @ManyToOne(() => User, { onDelete: 'SET NULL' })
  @JoinColumn()
  public user: User;

  @ManyToOne(() => Window, (window) => window.askChanges, {
    onDelete: 'SET NULL',
  })
  @JoinColumn()
  public window: Window;
}
